"""Chat completions endpoint streaming responses from Ollama."""

from __future__ import annotations

import json
from typing import Annotated, Any, Iterable, Literal

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

from ..config import Settings, get_settings
from ..dependencies.auth import verify_bearer_token
from ..rate_limit import limit_dependency

router = APIRouter(tags=["chat"], dependencies=[Depends(verify_bearer_token)])

chat_limit = limit_dependency("30/minute")


class ChatMessage(BaseModel):
    """Minimal chat message schema to mirror Open WebUI payloads."""

    role: Literal["system", "user", "assistant"]
    content: str


class ChatCompletionRequest(BaseModel):
    """Expected body for POST /api/v1/chat/completions."""

    model: str | None = Field(default=None, description="Target model name (Ollama route).")
    stream: bool = Field(default=True, description="Enable streaming responses.")
    messages: list[ChatMessage] = Field(default_factory=list)


@router.post("/chat/completions", summary="Chat completions proxy", dependencies=[Depends(chat_limit)])
async def chat_completions(
    payload: ChatCompletionRequest,
    settings: Annotated[Settings, Depends(get_settings)],
):
    """Stream tokens generated by Ollama following the OpenAI SSE contract."""

    if settings.ollama_base_url is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Ollama service not configured.",
        )

    if not payload.stream:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only streaming chat responses are supported.",
        )

    model_name = payload.model or settings.ollama_llm_model
    if not model_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No model provided and no default configured.",
        )

    messages = _to_langchain_messages(payload.messages)

    chat = ChatOllama(
        base_url=str(settings.ollama_base_url),
        model=model_name,
        temperature=0.1,
    )

    async def event_stream() -> Iterable[str]:
        try:
            async for chunk in chat.astream(messages):
                token = _chunk_text(chunk)
                if not token:
                    continue
                payload = {
                    "id": None,
                    "object": "chat.completion.chunk",
                    "model": model_name,
                    "choices": [
                        {
                            "index": 0,
                            "delta": {"content": token},
                            "finish_reason": None,
                        }
                    ],
                }
                yield _format_sse(payload)

            final_payload = {
                "id": None,
                "object": "chat.completion.chunk",
                "model": model_name,
                "choices": [
                    {
                        "index": 0,
                        "delta": {},
                        "finish_reason": "stop",
                    }
                ],
                "done": True,
            }
            yield _format_sse(final_payload)
            yield "data: [DONE]\n\n"
        except Exception as exc:  # pragma: no cover
            error_payload = {
                "error": str(exc),
            }
            yield _format_sse(error_payload)
            yield "data: [DONE]\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


def _to_langchain_messages(messages: list[ChatMessage]):
    converted = []
    for message in messages:
        if message.role == "system":
            converted.append(SystemMessage(content=message.content))
        elif message.role == "assistant":
            converted.append(AIMessage(content=message.content))
        else:
            converted.append(HumanMessage(content=message.content))
    return converted


def _chunk_text(chunk) -> str:
    def _stringify(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, list):
            parts: list[str] = []
            for item in value:
                if isinstance(item, dict) and "text" in item:
                    text_val = item["text"]
                    parts.append(str(text_val))
                else:
                    parts.append(str(item))
            return "".join(parts)
        if isinstance(value, str):
            return value
        text_attr = getattr(value, "text", None)
        if callable(text_attr):
            try:
                return str(text_attr())
            except TypeError:
                return str(text_attr)
        return str(value)

    if hasattr(chunk, "message") and getattr(chunk.message, "content", None):
        return _stringify(chunk.message.content)
    if hasattr(chunk, "delta") and getattr(chunk.delta, "content", None):
        return _stringify(chunk.delta.content)
    if hasattr(chunk, "text"):
        text_attr = chunk.text
        if callable(text_attr):
            try:
                return str(text_attr())
            except TypeError:
                return str(text_attr)
        return str(text_attr)
    if hasattr(chunk, "content"):
        return _stringify(chunk.content)
    return ""


def _format_sse(payload: dict[str, Any]) -> str:
    return f"data: {json.dumps(payload, ensure_ascii=False)}\n\n"
